### ISSUE TITLE
You're sending emails to npm contributors

### ISSUE THREAD

**Issue by chrisirhc** [marekventur/dependency-updater#23]
It looks like a script is generating PRs on this repository, and I think you should correct this immediately before you get marked as spam.

Please use a code block if you want to paste changelogs. That way, users of github won't be sent emails as it won't be treated like `@mentions`.

Like:

```
CHANGES:

@chrisirhc did x
```

**Comment by marekventur** [comment]
Thanks for your suggestion. I've disabled the script for now and will wrap changelogs in code blocks asap.

**Comment by chrisirhc** [comment]
No problem! Great! :+1:
